
lua:
  authorize:
    sha1: 7c1a0e2b18597d1dbfbb28985a6bd01796e0e78a
    seconds: 600
  token:
    sha1: dd772d67fd811eca4aee6e8a1c803d8c1de9c63f
    seconds: 3600
  getSession:
    sha1: b41da011bd36971042ecd130547f617cc3295eda
  pw:
    sha1: 0338b12e85eac5190afd685c6e201ff7f72f3b72


server:
  port: 8883

debug: false

logging:
  level:
    root: info
  tk:
    mybatis:
      springboot:
        mapper: trace

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/oauth2?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      stat-view-servlet:
        allow: true
  redis:
   database: 1
   host: 127.0.0.1
   port: 6379
   password:
   timeout: 0
   pool:
     max-active: 8
     max-wait: -1
     max-idle: 8
     min-idle: 0
