
app:
  name: oauth2
  domain: oauth2.net
  session:
    timeout: 10
  pwd:
    def: 123456

spring:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /static/**
  http:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  application:
    name: oauth2
  freemarker:
    request-context-attribute: req
    suffix: .html
    content-type: text/html
    enabled: true
    cache: false
    template-loader-path: classpath:/ftl/
    charset: UTF-8
    settings:
      number_format: '0.##'
  session:
    store-type: none
  aop:
    proxy-target-class: true

mybatis:
  type-aliases-package: net.foreworld.oauth2.model
  mapper-locations: classpath:mybatis/*.xml

mapper:
  mappers:
    - net.foreworld.mapper.MyMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

